# Generated by Django 5.1 on 2024-08-26 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_date_alter_user_followed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed',
            field=models.ManyToManyField(blank=True, related_name='user_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
